package org.mikezerosix.handlers;

/*

Executing command 'kick Little bastard' from client [FF00FF]Camalot
167762.600 Removing player with id clientId=97, entityId=22982
167762.600 GMSG: Little bastard left the game
167762.600 Removing observed entity 95
No objects f1o1r6 76t7h76e2 7.g6i60ve02n  .Epx6lia0tye0edr   EItDxh rwieeatrdee_ Cddoeml metWtrehidt re9r7e
:a
 dcl_=C97o,m mchW=1r
i
ter: cl=97, ch=2
167762.700 Exited thread_CommReader: cl=97, ch=2
167762.700 Exited thread_CommReader: cl=97, ch=1
Couldn't send RPC function 'RPC_SpawnParticleEffect'

Couldn't send RPC function 'RPC_SpawnParticleEffect'

167763.100 OnPlayerDisconnected 97
No objects for the given player ID were deleted 97
167767.900 OnPlayerConnected 100
167768.300 PlayerLogin: 585467957142809505/AllocatedID: 0/Little bastard/Alpha 9.1
167768.300 Token: FAAAADsVuxpdL7HaHQ4hCwEAEAFIIftTGAAAAAEAAAACAAAA0GBFfQAAAACnF6kADwAAALIAAAAyAAAABAAAAB0OIQsBABABstYDAFlQl7ZkAajAAAAAANED71NRswpUAQAVeAAAAAAAAAbxDXjc97FZegMcEqHSDonOaRmrTQRd4lwacKq1wSile2wXI5k05kR8BVQcDnlHtoTcEuHucFSE86Qd4oaaRsdSNuRKJyhGFV0f4viE353MQtfjwXwzwcwQqiWgbZeNBJylyjX78/73mxFIAbjN7kllFYS4wbN8BUahniVCCQt6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgi14D4JNeA8AUZwMgjV4D4IxeA0CMXgNggF4DAK1eA6CMXgOAil4DYIpeAwCMZwMgil4DoIleAwCKXgPgiV4D4IheAw==
167768.400 Player 'Little bastard' already allowed!
 */
public class CommandHandler implements TelnetOutputHandler {

    String COMMAND_TRIGGER = "Executing command";

    @Override public boolean match(String line) {
        return false;
    }

    @Override
    public void handleInput(String input) {

    }
}
